//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BronPc
    {
        public int idBronPc { get; set; }
        public string NumberTable { get; set; }
        public Nullable<int> idUsers { get; set; }
        public Nullable<int> idPc { get; set; }
    
        public virtual Pc Pc { get; set; }
        public virtual Users Users { get; set; }
    }
}
