//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazFood
    {
        public int idZakazFood { get; set; }
        public Nullable<int> idFood { get; set; }
        public Nullable<int> idUsers { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Users Users { get; set; }
    }
}
